#!/bin/bash

echo "Building for $1"

DG_PWD=`pwd`
DG_BASE=`basename $PWD`
echo "in directory $DG_BASE"
DG_POSTEXPORT="dch -l$1 -D $1 'rebuild for $1' --force-distribution"
#echo "postexport: $DG_POSTEXPORT"

if [[ "$DG_BASE" =~  ^fonts- ]]; then
  echo "Is a font package"
  if [[ "$1" == "precise" ]]; then
    echo "modify rules file for precise"
    DG_POSTEXPORT="dch -l$1 -D $1 --force-distribution 'rebuild for $1 with modified dpkg-builddeb rules' && sed -e 's/-Sextreme //g' debian/rules > debian/rules.precise && mv debian/rules.precise debian/rules && chmod +x debian/rules"
  fi
fi


DIST=$1 gbp buildpackage --git-dist=$1 --git-postexport="$DG_POSTEXPORT"
